import { Quiz, Student, StudentAttempt } from './types';

export const INITIAL_STUDENTS: Student[] = [
  { id: 'std-1', rollNo: 'CS-2024-042', name: 'Aarav Sharma', email: 'aarav.s@college.edu', division: 'DIV_A', batch: 'BATCH_A' },
  { id: 'std-2', rollNo: 'CS-2024-043', name: 'Aditi Deshmukh', email: 'aditi.d@college.edu', division: 'DIV_A', batch: 'BATCH_A' },
  { id: 'std-3', rollNo: 'CS-2024-055', name: 'Sneha Patil', email: 'sneha.p@college.edu', division: 'DIV_A', batch: 'BATCH_B' },
  { id: 'std-4', rollNo: 'CS-2024-068', name: 'Rohan Kulkarni', email: 'rohan.k@college.edu', division: 'DIV_A', batch: 'BATCH_C' },
  { id: 'std-5', rollNo: 'CS-2024-102', name: 'Kavya Pillai', email: 'kavya.p@college.edu', division: 'DIV_B', batch: 'BATCH_A' },
  { id: 'std-6', rollNo: 'CS-2024-118', name: 'Tanmay Joshi', email: 'tanmay.j@college.edu', division: 'DIV_B', batch: 'BATCH_B' },
];

export const INITIAL_QUIZZES: Quiz[] = [
  {
    id: 'quiz-dsa-1',
    title: 'Data Structures & Algorithms - Mid-Term',
    subjectCode: 'CS301',
    subjectName: 'Data Structures & Algorithms',
    description: 'Covers Trees, Binary Search Trees, Heaps, Graph Traversals, and Big-O notation.',
    timeLimitMinutes: 15,
    totalMarks: 10,
    passingMarks: 5,
    instructions: 'Select the correct answer for each multiple-choice question. Each question carries 2 marks. Click submit before the timer expires.',
    dueDate: '2026-08-25',
    dueTime: '23:59',
    shuffleQuestions: true,
    instantResults: true,
    createdAt: '2026-08-10',
    status: 'assigned',
    assignedTo: [
      { division: 'DIV_A', batches: ['BATCH_A', 'BATCH_B', 'BATCH_C'] },
      { division: 'DIV_B', batches: ['BATCH_A', 'BATCH_B', 'BATCH_C'] },
    ],
    questions: [
      {
        id: 'q1',
        text: 'What is the worst-case time complexity of searching in an unbalanced Binary Search Tree (BST)?',
        marks: 2,
        explanation: 'In the worst case (a skewed tree), BST operations degenerate to sequential traversal of a linked list, taking O(n) time.',
        options: [
          { id: 'q1_opt1', text: 'O(1)', isCorrect: false },
          { id: 'q1_opt2', text: 'O(log n)', isCorrect: false },
          { id: 'q1_opt3', text: 'O(n)', isCorrect: true },
          { id: 'q1_opt4', text: 'O(n log n)', isCorrect: false },
        ],
      },
      {
        id: 'q2',
        text: 'Which data structure operates on a First-In, First-Out (FIFO) principle?',
        marks: 2,
        explanation: 'A Queue adheres strictly to First-In, First-Out order where elements are inserted at the rear and removed from the front.',
        options: [
          { id: 'q2_opt1', text: 'Stack', isCorrect: false },
          { id: 'q2_opt2', text: 'Queue', isCorrect: true },
          { id: 'q2_opt3', text: 'Binary Tree', isCorrect: false },
          { id: 'q2_opt4', text: 'Max-Heap', isCorrect: false },
        ],
      },
      {
        id: 'q3',
        text: 'What is the minimum number of queues needed to implement a Stack?',
        marks: 2,
        explanation: 'A Stack (LIFO) can be simulated using 2 standard FIFO Queues by making either push or pop operation costly.',
        options: [
          { id: 'q3_opt1', text: '1 Queue', isCorrect: false },
          { id: 'q3_opt2', text: '2 Queues', isCorrect: true },
          { id: 'q3_opt3', text: '3 Queues', isCorrect: false },
          { id: 'q3_opt4', text: '4 Queues', isCorrect: false },
        ],
      },
      {
        id: 'q4',
        text: 'Which sorting algorithm has the best average-case and worst-case time complexity of O(n log n) with guaranteed stability?',
        marks: 2,
        explanation: 'Merge Sort guarantees O(n log n) in all cases (best, average, and worst) and is a stable sorting algorithm.',
        options: [
          { id: 'q4_opt1', text: 'Quick Sort', isCorrect: false },
          { id: 'q4_opt2', text: 'Merge Sort', isCorrect: true },
          { id: 'q4_opt3', text: 'Selection Sort', isCorrect: false },
          { id: 'q4_opt4', text: 'Bubble Sort', isCorrect: false },
        ],
      },
      {
        id: 'q5',
        text: 'In Graph Theory, which algorithm finds the shortest path between all pairs of vertices in O(V^3) time?',
        marks: 2,
        explanation: 'Floyd-Warshall algorithm uses dynamic programming to find shortest paths between all vertex pairs with O(V^3) runtime.',
        options: [
          { id: 'q5_opt1', text: 'Dijkstra\'s Algorithm', isCorrect: false },
          { id: 'q5_opt2', text: 'Prim\'s Algorithm', isCorrect: false },
          { id: 'q5_opt3', text: 'Floyd-Warshall Algorithm', isCorrect: true },
          { id: 'q5_opt4', text: 'Kruskal\'s Algorithm', isCorrect: false },
        ],
      },
    ],
  },
  {
    id: 'quiz-dbms-1',
    title: 'Database Normalization & SQL Queries',
    subjectCode: 'CS302',
    subjectName: 'Database Management Systems',
    description: 'Questions on 1NF, 2NF, 3NF, BCNF decomposition and relational algebra query optimization.',
    timeLimitMinutes: 10,
    totalMarks: 8,
    passingMarks: 4,
    instructions: 'Answer all 4 questions. Make sure to review functional dependencies before selecting your options.',
    dueDate: '2026-08-28',
    dueTime: '23:59',
    shuffleQuestions: false,
    instantResults: true,
    createdAt: '2026-08-11',
    status: 'assigned',
    assignedTo: [
      { division: 'DIV_A', batches: ['BATCH_A', 'BATCH_B'] },
      { division: 'DIV_B', batches: ['BATCH_A'] },
    ],
    questions: [
      {
        id: 'db_q1',
        text: 'A table is in 2NF if and only if it is in 1NF and what other condition is satisfied?',
        marks: 2,
        explanation: 'Second Normal Form (2NF) eliminates partial dependency — no non-prime attribute should be functionally dependent on a subset of any candidate key.',
        options: [
          { id: 'db_q1_opt1', text: 'No transitive dependencies exist', isCorrect: false },
          { id: 'db_q1_opt2', text: 'No partial dependencies on candidate keys', isCorrect: true },
          { id: 'db_q1_opt3', text: 'All columns contain foreign keys', isCorrect: false },
          { id: 'db_q1_opt4', text: 'Every determinant is a superkey', isCorrect: false },
        ],
      },
      {
        id: 'db_q2',
        text: 'Which SQL clause is evaluated first in a standard SELECT query execution plan?',
        marks: 2,
        explanation: 'SQL query execution logically starts with the FROM clause to identify and join the tables from which data is retrieved.',
        options: [
          { id: 'db_q2_opt1', text: 'WHERE', isCorrect: false },
          { id: 'db_q2_opt2', text: 'FROM', isCorrect: true },
          { id: 'db_q2_opt3', text: 'SELECT', isCorrect: false },
          { id: 'db_q2_opt4', text: 'GROUP BY', isCorrect: false },
        ],
      },
      {
        id: 'db_q3',
        text: 'What is the highest normal form where every functional dependency X -> Y requires X to be a superkey?',
        marks: 2,
        explanation: 'Boyce-Codd Normal Form (BCNF) strictly mandates that for every non-trivial functional dependency X -> Y, X must be a superkey.',
        options: [
          { id: 'db_q3_opt1', text: '1NF', isCorrect: false },
          { id: 'db_q3_opt2', text: '2NF', isCorrect: false },
          { id: 'db_q3_opt3', text: '3NF', isCorrect: false },
          { id: 'db_q3_opt4', text: 'BCNF', isCorrect: true },
        ],
      },
      {
        id: 'db_q4',
        text: 'Which ACID property guarantees that all operations in a database transaction complete successfully, or none do?',
        marks: 2,
        explanation: 'Atomicity ensures all-or-nothing execution: if any operation fails, the entire transaction is rolled back.',
        options: [
          { id: 'db_q4_opt1', text: 'Atomicity', isCorrect: true },
          { id: 'db_q4_opt2', text: 'Consistency', isCorrect: false },
          { id: 'db_q4_opt3', text: 'Isolation', isCorrect: false },
          { id: 'db_q4_opt4', text: 'Durability', isCorrect: false },
        ],
      },
    ],
  },
  {
    id: 'quiz-cn-1',
    title: 'Computer Networks: OSI Layer Architecture',
    subjectCode: 'CS304',
    subjectName: 'Computer Networks',
    description: 'Review of Application, Transport, Network, Data Link, and Physical layers.',
    timeLimitMinutes: 10,
    totalMarks: 6,
    passingMarks: 3,
    instructions: 'Test your understanding of protocol layers, packet headers, and network hardware.',
    dueDate: '2026-08-20',
    dueTime: '18:00',
    shuffleQuestions: false,
    instantResults: true,
    createdAt: '2026-08-05',
    status: 'assigned',
    assignedTo: [
      { division: 'DIV_A', batches: ['BATCH_A', 'BATCH_B', 'BATCH_C'] },
      { division: 'DIV_B', batches: ['BATCH_A', 'BATCH_B', 'BATCH_C'] },
    ],
    questions: [
      {
        id: 'cn_q1',
        text: 'At which OSI layer does IP (Internet Protocol) routing take place?',
        marks: 2,
        explanation: 'The Network Layer (Layer 3) handles logical IP addressing and packet routing across intermediate routers.',
        options: [
          { id: 'cn_q1_opt1', text: 'Data Link Layer (Layer 2)', isCorrect: false },
          { id: 'cn_q1_opt2', text: 'Network Layer (Layer 3)', isCorrect: true },
          { id: 'cn_q1_opt3', text: 'Transport Layer (Layer 4)', isCorrect: false },
          { id: 'cn_q1_opt4', text: 'Session Layer (Layer 5)', isCorrect: false },
        ],
      },
      {
        id: 'cn_q2',
        text: 'Which transport protocol is connection-oriented and provides reliable, ordered data delivery with flow control?',
        marks: 2,
        explanation: 'TCP (Transmission Control Protocol) is connection-oriented, provides sequence numbering, acknowledgments, and flow control.',
        options: [
          { id: 'cn_q2_opt1', text: 'UDP', isCorrect: false },
          { id: 'cn_q2_opt2', text: 'TCP', isCorrect: true },
          { id: 'cn_q2_opt3', text: 'ICMP', isCorrect: false },
          { id: 'cn_q2_opt4', text: 'ARP', isCorrect: false },
        ],
      },
      {
        id: 'cn_q3',
        text: 'What is the default port number used by secure HTTPS communication?',
        marks: 2,
        explanation: 'HTTPS operates by default over TCP port 443 with TLS encryption (standard HTTP uses port 80).',
        options: [
          { id: 'cn_q3_opt1', text: '80', isCorrect: false },
          { id: 'cn_q3_opt2', text: '8080', isCorrect: false },
          { id: 'cn_q3_opt3', text: '443', isCorrect: true },
          { id: 'cn_q3_opt4', text: '22', isCorrect: false },
        ],
      },
    ],
  },
];

// Pre-seeded attempts so "See Result" works immediately for completed quizzes out of the box!
export const INITIAL_ATTEMPTS: StudentAttempt[] = [
  {
    id: 'att-cn-1-std-1',
    quizId: 'quiz-cn-1',
    studentId: 'std-1',
    studentName: 'Aarav Sharma',
    studentRoll: 'CS-2024-042',
    division: 'DIV_A',
    batch: 'BATCH_A',
    startedAt: '2026-08-14T14:10:00Z',
    submittedAt: '2026-08-14T14:16:30Z',
    timeSpentSeconds: 390,
    totalScore: 6,
    maxScore: 6,
    scorePercentage: 100,
    passed: true,
    answers: [
      {
        questionId: 'cn_q1',
        selectedOptionId: 'cn_q1_opt2',
        isCorrect: true,
        marksObtained: 2,
      },
      {
        questionId: 'cn_q2',
        selectedOptionId: 'cn_q2_opt2',
        isCorrect: true,
        marksObtained: 2,
      },
      {
        questionId: 'cn_q3',
        selectedOptionId: 'cn_q3_opt3',
        isCorrect: true,
        marksObtained: 2,
      },
    ],
  },
  {
    id: 'att-dsa-1-std-3',
    quizId: 'quiz-dsa-1',
    studentId: 'std-3',
    studentName: 'Sneha Patil',
    studentRoll: 'CS-2024-055',
    division: 'DIV_A',
    batch: 'BATCH_B',
    startedAt: '2026-08-15T09:00:00Z',
    submittedAt: '2026-08-15T09:12:15Z',
    timeSpentSeconds: 735,
    totalScore: 8,
    maxScore: 10,
    scorePercentage: 80,
    passed: true,
    answers: [
      { questionId: 'q1', selectedOptionId: 'q1_opt3', isCorrect: true, marksObtained: 2 },
      { questionId: 'q2', selectedOptionId: 'q2_opt2', isCorrect: true, marksObtained: 2 },
      { questionId: 'q3', selectedOptionId: 'q3_opt2', isCorrect: true, marksObtained: 2 },
      { questionId: 'q4', selectedOptionId: 'q4_opt1', isCorrect: false, marksObtained: 0 },
      { questionId: 'q5', selectedOptionId: 'q5_opt3', isCorrect: true, marksObtained: 2 },
    ],
  },
];
