/**
 * reportService.js
 * ------------------------------------------------------------------
 * Handles real PDF generation (jsPDF) and real Excel generation
 * (SheetJS). Also manages Export History persistence in localStorage.
 * ------------------------------------------------------------------
 */

(function (global) {
  'use strict';

  const DB = global.MOCK_DB;
  const HISTORY_KEY = 'sma_export_history_v1';

  function nowStr() {
    return new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' });
  }

  function getHistory() {
    try {
      return JSON.parse(localStorage.getItem(HISTORY_KEY)) || [];
    } catch (e) { return []; }
  }

  function saveHistoryEntry(entry) {
    const history = getHistory();
    history.unshift({ id: 'RPT' + Date.now(), generatedDate: nowStr(), generatedBy: 'Faculty User', status: 'Completed', ...entry });
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history.slice(0, 100)));
    return history;
  }

  function deleteHistoryEntry(id) {
    const history = getHistory().filter((h) => h.id !== id);
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history));
    return history;
  }

  // ---------------- PDF helpers ----------------
  function pdfHeader(doc, title) {
    const pageWidth = doc.internal.pageSize.getWidth();
    doc.setFillColor(24, 41, 66);
    doc.rect(0, 0, pageWidth, 26, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12.5);
    doc.setFont('helvetica', 'bold');
    doc.text(DB.meta.institution, 14, 11);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(DB.meta.department, 14, 17);
    doc.setFontSize(9.5);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 14, 23.5);

    doc.setTextColor(90, 90, 90);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.text(`Generated: ${nowStr()}`, pageWidth - 14, 11, { align: 'right' });
    doc.text('Academic Year: 2026-27  |  Sem 5', pageWidth - 14, 16, { align: 'right' });
    doc.setTextColor(20, 20, 20);
  }

  function pdfFooter(doc) {
    const pageCount = doc.internal.getNumberOfPages();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setDrawColor(225, 225, 225);
      doc.line(14, pageHeight - 14, pageWidth - 14, pageHeight - 14);
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text('Generated by Student Marks Analytics & CO Attainment Tool', 14, pageHeight - 9);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 9, { align: 'right' });
    }
  }

  function newDoc() {
    const { jsPDF } = window.jspdf;
    return new jsPDF({ unit: 'mm', format: 'a4' });
  }

  // ---------------- Individual Marksheet PDF ----------------
  async function generateMarksheetPDF(studentId) {
    const student = await window.ApiService.getStudentById(studentId);
    if (!student) throw new Error('Student not found');
    const doc = newDoc();
    pdfHeader(doc, 'Individual Marksheet');

    doc.setFontSize(10.5);
    doc.setTextColor(20, 20, 20);
    let y = 36;
    const rows = [
      ['Student Name', student.name, 'Roll No.', student.rollNo],
      ['PRN', student.prn, 'Branch', student.branch],
      ['Semester', student.semester, 'Batch', student.batch],
    ];
    rows.forEach((r) => {
      doc.setFont('helvetica', 'bold'); doc.text(r[0] + ':', 14, y);
      doc.setFont('helvetica', 'normal'); doc.text(String(r[1]), 45, y);
      doc.setFont('helvetica', 'bold'); doc.text(r[2] + ':', 110, y);
      doc.setFont('helvetica', 'normal'); doc.text(String(r[3]), 140, y);
      y += 6;
    });

    y += 3;
    doc.autoTable({
      startY: y,
      head: [['Subject', 'Code', 'Percentage', 'Grade']],
      body: student.subjectPerformance.map((s) => [s.subject, s.code, s.percentage + '%', window.AnalyticsService.calculateGrade(s.percentage)]),
      theme: 'grid',
      headStyles: { fillColor: [24, 41, 66] },
      styles: { fontSize: 9 },
    });

    y = doc.lastAutoTable.finalY + 8;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10.5);
    doc.text('Course Outcome (CO) Attainment', 14, y);
    y += 3;
    doc.autoTable({
      startY: y,
      head: [['CO', 'Target %', 'Attainment %', 'Status']],
      body: student.coPerformance.map((c) => [c.co, c.target + '%', c.attainment + '%', c.attainment >= c.target ? 'Achieved' : 'Below Target']),
      theme: 'grid',
      headStyles: { fillColor: [24, 41, 66] },
      styles: { fontSize: 9 },
    });

    y = doc.lastAutoTable.finalY + 10;
    doc.setFillColor(245, 247, 250);
    doc.rect(14, y - 5, 182, 20, 'F');
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10);
    doc.text(`Overall Percentage: ${student.overallPercentage}%`, 18, y);
    doc.text(`Grade: ${student.grade}`, 90, y);
    doc.text(`Result: ${student.passStatus.toUpperCase()}`, 140, y);
    doc.text(`Class Rank: ${student.rank} / ${student.totalStudents}`, 18, y + 8);
    doc.text(`CO Attainment (avg): ${student.coAttainmentOverall}%`, 90, y + 8);

    y += 26;
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9);
    doc.text('_____________________________', 14, y + 20);
    doc.text('Class Coordinator', 14, y + 25);
    doc.text('_____________________________', 120, y + 20);
    doc.text('Head of Department', 120, y + 25);

    pdfFooter(doc);
    const fileName = `Marksheet_${student.rollNo}.pdf`;
    doc.save(fileName);
    saveHistoryEntry({ name: fileName, type: 'Individual Marksheet', format: 'PDF' });
    return fileName;
  }

  // ---------------- Class Performance PDF ----------------
  async function generateClassPerformancePDF(filters) {
    const dash = await window.ApiService.getDashboardAnalytics(filters);
    const students = await window.ApiService.getStudents(filters);
    const doc = newDoc();
    pdfHeader(doc, 'Class Performance Report');

    let y = 36;
    doc.setFontSize(10.5); doc.setFont('helvetica', 'bold');
    doc.text('Class Statistics', 14, y); y += 4;
    doc.autoTable({
      startY: y,
      head: [['Total Students', 'Average Marks', 'Pass %', 'At-Risk Students']],
      body: [[dash.kpis.totalStudents, dash.kpis.averageMarks + '%', dash.kpis.passPercentage + '%', dash.kpis.atRiskStudents]],
      theme: 'grid', headStyles: { fillColor: [24, 41, 66] }, styles: { fontSize: 9 },
    });

    y = doc.lastAutoTable.finalY + 8;
    doc.setFont('helvetica', 'bold'); doc.text('Grade Distribution', 14, y); y += 4;
    doc.autoTable({
      startY: y,
      head: [['Grade', 'Students', 'Percentage']],
      body: dash.gradeDistribution.map((g) => [g.grade, g.count, g.percentage + '%']),
      theme: 'grid', headStyles: { fillColor: [24, 41, 66] }, styles: { fontSize: 9 },
    });

    y = doc.lastAutoTable.finalY + 8;
    doc.setFont('helvetica', 'bold'); doc.text('Top Performers', 14, y); y += 4;
    doc.autoTable({
      startY: y,
      head: [['Rank', 'Roll No.', 'Name', 'Average %', 'Grade']],
      body: students.slice(0, 5).map((s) => [s.rank, s.rollNo, s.name, s.average + '%', s.grade]),
      theme: 'grid', headStyles: { fillColor: [39, 118, 88] }, styles: { fontSize: 9 },
    });

    y = doc.lastAutoTable.finalY + 8;
    doc.setFont('helvetica', 'bold'); doc.text('At-Risk Students', 14, y); y += 4;
    const atRisk = students.filter((s) => s.risk === 'At Risk');
    doc.autoTable({
      startY: y,
      head: [['Roll No.', 'Name', 'Average %', 'Risk']],
      body: atRisk.length ? atRisk.map((s) => [s.rollNo, s.name, s.average + '%', s.risk]) : [['-', 'No at-risk students in this selection', '-', '-']],
      theme: 'grid', headStyles: { fillColor: [178, 58, 58] }, styles: { fontSize: 9 },
    });

    pdfFooter(doc);
    const fileName = 'Class_Performance_Report.pdf';
    doc.save(fileName);
    saveHistoryEntry({ name: fileName, type: 'Class Performance Report', format: 'PDF' });
    return fileName;
  }

  // ---------------- CO Attainment PDF ----------------
  async function generateCOReportPDF(filters) {
    const co = await window.ApiService.getCOAttainment(filters);
    const doc = newDoc();
    pdfHeader(doc, 'CO Attainment Report');
    doc.autoTable({
      startY: 36,
      head: [['CO', 'Target %', 'Attainment %', 'Gap', 'Status', 'Students Achieved']],
      body: co.map((c) => [c.id, c.target + '%', c.attainment + '%', c.gap, c.status, `${c.studentsAchieved}/${c.totalStudents}`]),
      theme: 'grid', headStyles: { fillColor: [24, 41, 66] }, styles: { fontSize: 9 },
    });
    let y = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(9); doc.setFont('helvetica', 'italic');
    doc.text('Note: CO Attainment is computed using a Demo Calculation Method (class average of', 14, y);
    doc.text('per-student internal assessment performance mapped to each Course Outcome).', 14, y + 5);
    pdfFooter(doc);
    const fileName = 'CO_Attainment_Report.pdf';
    doc.save(fileName);
    saveHistoryEntry({ name: fileName, type: 'CO Attainment Report', format: 'PDF' });
    return fileName;
  }

  // ---------------- PO Attainment PDF ----------------
  async function generatePOReportPDF(filters) {
    const po = await window.ApiService.getPOAttainment(filters);
    const doc = newDoc();
    pdfHeader(doc, 'PO Attainment Report');
    doc.autoTable({
      startY: 36,
      head: [['PO', 'Title', 'Target %', 'Attainment %', 'Gap', 'Status']],
      body: po.map((p) => [p.id, p.title, p.target + '%', p.attainment + '%', p.gap, p.status]),
      theme: 'grid', headStyles: { fillColor: [24, 41, 66] }, styles: { fontSize: 8.5 },
      columnStyles: { 1: { cellWidth: 55 } },
    });
    let y = doc.lastAutoTable.finalY + 10;
    const achieved = po.filter((p) => p.status === 'Achieved').length;
    doc.setFontSize(10); doc.setFont('helvetica', 'bold');
    doc.text(`Summary: ${achieved} of ${po.length} Programme Outcomes have achieved their target attainment.`, 14, y);
    pdfFooter(doc);
    const fileName = 'PO_Attainment_Report.pdf';
    doc.save(fileName);
    saveHistoryEntry({ name: fileName, type: 'PO Attainment Report', format: 'PDF' });
    return fileName;
  }

  // ---------------- Generic report dispatcher used by Report Center ----------------
  async function generateReport(reportType, options) {
    options = options || {};
    switch (reportType) {
      case 'individual-marksheet':
        return generateMarksheetPDF(options.studentId);
      case 'class-performance':
        return generateClassPerformancePDF(options.filters);
      case 'co-attainment':
        return generateCOReportPDF(options.filters);
      case 'po-attainment':
        return generatePOReportPDF(options.filters);
      case 'assessment-analysis':
        return generateAssessmentAnalysisPDF(options.filters);
      case 'student-risk':
        return generateStudentRiskPDF(options.filters);
      case 'complete-analytics':
        return generateCompleteAnalyticsPDF(options.filters);
      default:
        throw new Error('Unknown report type');
    }
  }

  async function generateAssessmentAnalysisPDF(filters) {
    const data = await window.ApiService.getAssessmentAnalytics(filters);
    const doc = newDoc();
    pdfHeader(doc, 'Assessment Analysis Report');
    doc.autoTable({
      startY: 36,
      head: [['Assessment', 'Type', 'Average', 'Highest', 'Lowest', 'Median', 'Std Dev', 'Pass %']],
      body: data.map((a) => [a.name, a.type, a.average, a.highest, a.lowest, a.median, a.stdDev, a.passPercentage + '%']),
      theme: 'grid', headStyles: { fillColor: [24, 41, 66] }, styles: { fontSize: 8.5 },
    });
    pdfFooter(doc);
    const fileName = 'Assessment_Analysis_Report.pdf';
    doc.save(fileName);
    saveHistoryEntry({ name: fileName, type: 'Assessment Analysis Report', format: 'PDF' });
    return fileName;
  }

  async function generateStudentRiskPDF(filters) {
    const students = await window.ApiService.getStudents(filters);
    const doc = newDoc();
    pdfHeader(doc, 'Student Risk Report');
    doc.autoTable({
      startY: 36,
      head: [['Roll No.', 'Name', 'Average %', 'Attendance %', 'Risk']],
      body: students.filter((s) => s.risk === 'At Risk' || s.risk === 'Average')
        .map((s) => [s.rollNo, s.name, s.average + '%', s.attendance + '%', s.risk]),
      theme: 'grid', headStyles: { fillColor: [178, 58, 58] }, styles: { fontSize: 9 },
    });
    pdfFooter(doc);
    const fileName = 'Student_Risk_Report.pdf';
    doc.save(fileName);
    saveHistoryEntry({ name: fileName, type: 'Student Risk Report', format: 'PDF' });
    return fileName;
  }

  async function generateCompleteAnalyticsPDF(filters) {
    const dash = await window.ApiService.getDashboardAnalytics(filters);
    const co = await window.ApiService.getCOAttainment(filters);
    const po = await window.ApiService.getPOAttainment(filters);
    const doc = newDoc();
    pdfHeader(doc, 'Complete Academic Analytics Report');
    let y = 36;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10.5);
    doc.text('Class Overview', 14, y); y += 4;
    doc.autoTable({
      startY: y,
      head: [['Total Students', 'Average Marks', 'Pass %', 'Overall CO %', 'Overall PO %', 'At-Risk']],
      body: [[dash.kpis.totalStudents, dash.kpis.averageMarks + '%', dash.kpis.passPercentage + '%', dash.kpis.overallCOAttainment + '%', dash.kpis.overallPOAttainment + '%', dash.kpis.atRiskStudents]],
      theme: 'grid', headStyles: { fillColor: [24, 41, 66] }, styles: { fontSize: 8.5 },
    });
    y = doc.lastAutoTable.finalY + 8;
    doc.setFont('helvetica', 'bold'); doc.text('CO Attainment', 14, y); y += 4;
    doc.autoTable({
      startY: y, head: [['CO', 'Target', 'Attainment', 'Status']],
      body: co.map((c) => [c.id, c.target + '%', c.attainment + '%', c.status]),
      theme: 'grid', headStyles: { fillColor: [24, 41, 66] }, styles: { fontSize: 8.5 },
    });
    doc.addPage();
    pdfHeader(doc, 'Complete Academic Analytics Report (contd.)');
    y = 36;
    doc.setFont('helvetica', 'bold'); doc.text('PO Attainment', 14, y); y += 4;
    doc.autoTable({
      startY: y, head: [['PO', 'Target', 'Attainment', 'Status']],
      body: po.map((p) => [p.id, p.target + '%', p.attainment + '%', p.status]),
      theme: 'grid', headStyles: { fillColor: [24, 41, 66] }, styles: { fontSize: 8.5 },
    });
    pdfFooter(doc);
    const fileName = 'Complete_Academic_Analytics_Report.pdf';
    doc.save(fileName);
    saveHistoryEntry({ name: fileName, type: 'Complete Academic Analytics Report', format: 'PDF' });
    return fileName;
  }

  // ---------------- Excel exports (SheetJS, real .xlsx) ----------------
  function downloadWorkbook(wb, fileName) {
    XLSX.writeFile(wb, fileName);
  }

  async function exportClassPerformanceExcel(filters) {
    const students = await window.ApiService.getStudents(filters);
    const sheetRows = [];
    students.forEach((s) => {
      DB.subjects.forEach((subj) => {
        const subjMarks = DB.marks.filter((m) => m.studentId === s.id && m.subjectId === subj.id);
        const obtained = subjMarks.reduce((a, b) => a + b.obtained, 0);
        const max = subjMarks.reduce((a, b) => a + b.maxMarks, 0);
        const pct = window.AnalyticsService.calculatePercentage(obtained, max);
        sheetRows.push({
          'Roll No': s.rollNo, 'Name': s.name, 'Subject': subj.name,
          'Marks': obtained, 'Max Marks': max, 'Percentage': +pct.toFixed(1),
          'Grade': window.AnalyticsService.calculateGrade(pct), 'CO Attainment': s.coAttainment, 'Risk': s.risk,
        });
      });
    });
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(sheetRows), 'Class Performance');
    const fileName = 'Class_Performance.xlsx';
    downloadWorkbook(wb, fileName);
    saveHistoryEntry({ name: fileName, type: 'Class Performance Report', format: 'Excel' });
    return fileName;
  }

  async function exportCOExcel(filters) {
    const co = await window.ApiService.getCOAttainment(filters);
    const rows = co.map((c) => ({ CO: c.id, Target: c.target, Attainment: c.attainment, Gap: c.gap, Status: c.status }));
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), 'CO Attainment');
    const fileName = 'CO_Attainment.xlsx';
    downloadWorkbook(wb, fileName);
    saveHistoryEntry({ name: fileName, type: 'CO Attainment Report', format: 'Excel' });
    return fileName;
  }

  async function exportPOExcel(filters) {
    const po = await window.ApiService.getPOAttainment(filters);
    const rows = po.map((p) => ({ PO: p.id, Target: p.target, Attainment: p.attainment, Gap: p.gap, Status: p.status }));
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), 'PO Attainment');
    const fileName = 'PO_Attainment.xlsx';
    downloadWorkbook(wb, fileName);
    saveHistoryEntry({ name: fileName, type: 'PO Attainment Report', format: 'Excel' });
    return fileName;
  }

  async function exportStudentMarksExcel(filters) {
    const students = resolveStudentsSafe(filters);
    const rows = [];
    DB.marks.filter((m) => students.some((s) => s.id === m.studentId)).forEach((m) => {
      const s = DB.students.find((x) => x.id === m.studentId);
      const subj = DB.subjects.find((x) => x.id === m.subjectId);
      const a = DB.assessments.find((x) => x.id === m.assessmentId);
      rows.push({
        'Student': s.name, 'Subject': subj.name, 'Assessment': a.name,
        'Marks': m.obtained, 'Maximum Marks': m.maxMarks,
        'Percentage': +window.AnalyticsService.calculatePercentage(m.obtained, m.maxMarks).toFixed(1),
      });
    });
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(rows), 'Student Marks');
    const fileName = 'Student_Marks.xlsx';
    downloadWorkbook(wb, fileName);
    saveHistoryEntry({ name: fileName, type: 'Student Marks Export', format: 'Excel' });
    return fileName;
  }

  function resolveStudentsSafe(filters) {
    filters = filters || {};
    let students = DB.students;
    if (filters.batch && filters.batch !== 'All Batches') students = students.filter((s) => s.batch === filters.batch);
    return students;
  }

  async function exportExcel(reportType, filters) {
    switch (reportType) {
      case 'class-performance': return exportClassPerformanceExcel(filters);
      case 'co-attainment': return exportCOExcel(filters);
      case 'po-attainment': return exportPOExcel(filters);
      case 'student-marks': return exportStudentMarksExcel(filters);
      default: throw new Error('Excel export not available for this report type');
    }
  }

  global.ReportService = {
    generateReport,
    generateMarksheetPDF,
    exportExcel,
    getHistory,
    saveHistoryEntry,
    deleteHistoryEntry,
  };
})(window);
